--
-- Dumping data for table `mktg_menu_item`
--

INSERT INTO `mktg_menu_item` (`id`, `mktg_material_id`, `title`, `slug`, `description`, `status`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES
(1, 1, 'Letterhead / Followers', 'letterhead-followers', 'What better way to introduce your business to the world than through professional full-colour brochures. A versatile medium, brochures can be used for a variety of marketing needs, as well as a physical keep sake that customers can keep until they need your product or service.Printed CMYK on both sides on matt or gloss 170GSM stock, these tri-fold brochures are both high quality and durable.', 'open', 6, 0, '2016-07-31 23:09:40', '2016-07-31 23:09:40'),
(2, 1, 'With Comp Slip', 'with-comp-slip', 'What better way to introduce your business to the world than through professional full-colour brochures. A versatile medium, brochures can be used for a variety of marketing needs, as well as a physical keep sake that customers can keep until they need your product or service.Printed CMYK on both sides on matt or gloss 170GSM stock, these tri-fold brochures are both high quality and durable.', 'open', 6, 0, '2016-07-31 23:12:14', '2016-07-31 23:12:14'),
(3, 1, 'Evelopes', 'evelopes', 'What better way to introduce your business to the world than through professional full-colour brochures. A versatile medium, brochures can be used for a variety of marketing needs, as well as a physical keep sake that customers can keep until they need your product or service.Printed CMYK on both sides on matt or gloss 170GSM stock, these tri-fold brochures are both high quality and durable.', 'open', 6, 0, '2016-08-01 04:20:44', '2016-08-01 04:20:44'),
(4, 1, 'Presentation folder', 'presentation-folder', 'What better way to introduce your business to the world than through professional full-colour brochures. A versatile medium, brochures can be used for a variety of marketing needs, as well as a physical keep sake that customers can keep until they need your product or service.Printed CMYK on both sides on matt or gloss 170GSM stock, these tri-fold brochures are both high quality and durable.', 'open', 6, 6, '2016-08-01 04:28:26', '2016-08-01 04:29:37'),
(5, 1, 'Forms', 'forms', 'What better way to introduce your business to the world than through professional full-colour brochures. A versatile medium, brochures can be used for a variety of marketing needs, as well as a physical keep sake that customers can keep until they need your product or service.Printed CMYK on both sides on matt or gloss 170GSM stock, these tri-fold brochures are both high quality and durable.', 'open', 6, 0, '2016-08-01 04:35:50', '2016-08-01 04:35:50'),
(6, 1, 'Carbon Books (NCR)', 'carbon-books-ncr', 'What better way to introduce your business to the world than through professional full-colour brochures. A versatile medium, brochures can be used for a variety of marketing needs, as well as a physical keep sake that customers can keep until they need your product or service.Printed CMYK on both sides on matt or gloss 170GSM stock, these tri-fold brochures are both high quality and durable.', 'open', 6, 0, '2016-08-01 04:38:46', '2016-08-01 04:38:46'),
(7, 2, 'Tear Drop Flag', 'tear-drop-flag', 'What better way to introduce your business to the world than through professional full-colour brochures. A versatile medium, brochures can be used for a variety of marketing needs, as well as a physical keep sake that customers can keep until they need your product or service.Printed CMYK on both sides on matt or gloss 170GSM stock, these tri-fold brochures are both high quality and durable.', 'open', 6, 3, '2016-08-01 04:42:05', '2016-08-02 01:35:33'),
(8, 1, 'Directional signs', 'directional-signs', 'What better way to introduce your business to the world than through professional full-colour brochures. A versatile medium, brochures can be used for a variety of marketing needs, as well as a physical keep sake that customers can keep until they need your product or service.Printed CMYK on both sides on matt or gloss 170GSM stock, these tri-fold brochures are both high quality and durable.', 'open', 6, 0, '2016-08-01 04:48:17', '2016-08-01 04:48:17'),
(9, 3, 'Vynle stickers outdoor (SOLD)', 'vynle-stickers-outdoor-sold', 'What better way to introduce your business to the world than through professional full-colour brochures. A versatile medium, brochures can be used for a variety of marketing needs, as well as a physical keep sake that customers can keep until they need your product or service.Printed CMYK on both sides on matt or gloss 170GSM stock, these tri-fold brochures are both high quality and durable.', 'open', 3, 0, '2016-08-02 01:44:40', '2016-08-02 01:44:40'),
(10, 2, 'Pull Up Banner', 'pull-up-banner', 'What better way to introduce your business to the world than through professional full-colour brochures. A versatile medium, brochures can be used for a variety of marketing needs, as well as a physical keep sake that customers can keep until they need your product or service.Printed CMYK on both sides on matt or gloss 170GSM stock, these tri-fold brochures are both high quality and durable.', 'open', 3, 0, '2016-08-02 04:07:27', '2016-08-02 04:07:27'),
(11, 3, 'Congratulatory Pack', 'congratulatory-pack', 'What better way to introduce your business to the world than through professional full-colour brochures. A versatile medium, brochures can be used for a variety of marketing needs, as well as a physical keep sake that customers can keep until they need your product or service.Printed CMYK on both sides on matt or gloss 170GSM stock, these tri-fold brochures are both high quality and durable.', 'open', 3, 0, '2016-08-03 00:50:12', '2016-08-03 00:50:12');